<?php

/**
 * Created by PhpStorm.
 * User: moon
 * Date: 2016/3/10
 * Time: 21:14
 */
require_once("ShopProduct.php");

class BookProduct extends ShopProduct
{
    public $numPages = 0;

    function __construct($title, $firstName, $mainName, $price, $numPages)
    {
        parent::__construct($title, $firstName, $mainName, $price);
        $this->numPages = $numPages;
    }

    function getNumberOfPages()
    {
        return $this->numPages;
    }

    function getSummaryLine()
    {
        $base = parent::getSummaryLine(); // TODO: Change the autogenerated stub
//        $base = "$this->title ({$this->producerMainName}, ";
//        $base .= "{$this->producerFirstName} )";
        $base .= ": page count - {$this->numPages}";
        return $base;
    }

    function getPrice()
    {
        return $this->price;
    }
}