<?php

/**
 * Created by PhpStorm.
 * User: moon
 * Date: 2016/3/10
 * Time: 21:09
 */
require_once("ShopProduct.php");

class CDProduct extends ShopProduct
{
    public $playLength = 0;

    function __construct($title, $firstName, $mainName, $price, $playLength)
    {
        parent::__construct($title, $firstName, $mainName, $price);
        $this->playLength = $playLength;
    }

    function getPlayLength()
    {
        return $this->playLength;
    }

    function getSummaryLine()
    {
        $base = parent::getSummaryLine(); // TODO: Change the autogenerated stub
        $base .= ": playing time - {$this->playLength}";
        return $base;
    }
}